# Site settings
title: Women in Computer Science at Pitt!
email: wics.pitt@outlook.com
url: https://wicspitt.github.io
description: "Welcome, the Women in Computer Science at the University of Pittsburgh is a club that strives for success within the field of computer science! We hold amazing speaker panels, networking opportunities, and much more! Be sure to connect with us on the many platforms available."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FFA4CE'
  links: '#219ab3'

# Footer settings
footer: wics.pitt@outlook.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/wics_pitt/?hl=en
  - title: discord
    url: https://discord.gg/FcwGvbzHMn
  - title: mailing List
    url: https://forms.gle/CZnRfMAvijNXSHLH6

# Build settings
markdown: kramdown
permalink: pretty
