# Site settings
title: Women in Computer Science at Pitt!
email: wics.pitt@outlook.com
url: https://wicspitt.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: wics.pitt@outlook.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://www.instagram.com/wics_pitt/?hl=en
  - title: Discord
    url: https://discord.gg/FcwGvbzHMn
  - title: Mailing List
    url: https://forms.gle/CZnRfMAvijNXSHLH6

# Build settings
markdown: kramdown
permalink: pretty
